### ISSUE TITLE
Cannot change App Store URL (v.8.8.0)

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/DataspaceConnectorUI#123]
When editing the app store entry I can change the Title but not the URL:

![grafik](https://user-images.githubusercontent.com/4161673/151515064-06ec2664-ea30-454d-96bf-fbe5a8df2e3b.png)

**Comment by BastianWel** [comment]
This was a requirement for the UI for brokers and app stores. 
Changing the URL had to be done by creating a new broker/app store.
I'll check back to see if that's still necessary.

**Comment by sebplorenz** [comment]
If it is still necessary, can you grey-out the URL field, so that it becomes obvious that the URL cannot be changed. Because at the moment the field gets highlighted (green underscore) when I click on it.

**Comment by BastianWel** [comment]
Editing the URL for brokers and app stores is disabled, because i.e. when chaning the broker URL, the user might think that all his resources that were already registered at this broker will be now registered at the new URL.
This is not working currently an an implementation would be too time-consuming. 
Therefore, currently the simple solution is that the URL cannot be edited and a new broker must be created when the URL is changed, so that it is obvious to the user that he must re-register the resources there.
The URL is now displayed as a label when editing (since 6079397), so that it is clear to the user that editing is not possible.
