### ISSUE TITLE
Route still there after delete Ressource

### ISSUE THREAD

**Issue by HeinrichPet** [International-Data-Spaces-Association/DataspaceConnectorUI#57]
Hi,

the mini route is automatically deployed when you add a new IDS Ressource.
But when you delete the IDS Ressource the route is still there.

Best regards,
Heinrich

**Comment by BastianWel** [comment]
Currently not easy to implement, because the resource and the route are only linked via artifact ID. 
I need to get all routes via API call, search for that ID which will only find the last sub route. 
After that I need to find the main route with the sub route ID and also delete this main route and all other sub routes.

For the next release, we decided not to delete the associated route when deleting a resource.
